<?php declare( strict_types = 1 );

use Isolated\Symfony\Component\Finder\Finder;

/**
 * Builds a php-scoper config tailored for a WordPress plugin.
 *
 * Reads `wp-core-calls.json` (auto-generated by FindWPCoreCalls) from the project root
 * to discover which WordPress Core functions and classes the plugin actually uses, then
 * configures php-scoper to leave those references unprefixed at runtime.
 *
 * PSR namespaces (Psr\*) are excluded from scoping. PSR interfaces are designed for
 * cross-plugin interop — scoping them per-plugin would create incompatible interface
 * declarations between plugins shipping the same PSR version, defeating the purpose.
 *
 * @param array{
 *     project_dir?: string,
 *     finders?: list<Finder>,
 *     exclude_classes?: list<string>,
 *     exclude_functions?: list<string>,
 *     exclude_namespaces?: list<string>,
 *     patchers?: list<callable>,
 * } $overrides
 *
 * @return array
 */
return static function ( array $overrides = array() ): array {
	$project_dir = $overrides['project_dir'] ?? getcwd();

	$wp_calls_path = $project_dir . '/wp-core-calls.json';
	$wp_calls      = is_file( $wp_calls_path )
		? json_decode( file_get_contents( $wp_calls_path ), true, 512, JSON_THROW_ON_ERROR )
		: array( 'classes' => array(), 'functions' => array() );

	// Strips the scoping prefix from any references to WordPress Core functions or classes
	// inside scoped files. The `exclude-functions`/`exclude-classes` directives prevent
	// prefixing of direct calls, but string-based references (e.g., `function_exists()`
	// arguments, `use` statements emitted from concatenated strings) can still get
	// inadvertently prefixed. This patcher cleans those up post-scoping.
	$wp_reference_stripper = static function ( string $file_path, string $prefix, string $content ) use ( $wp_calls ): string {
		foreach ( $wp_calls['functions'] as $function ) {
			$content = str_replace( '\\' . $prefix . '\\' . $function . '(', '\\' . $function . '(', $content );
			$content = str_replace( "function_exists('" . $prefix . "\\\\" . $function, "function_exists('\\" . $function, $content );
		}
		foreach ( $wp_calls['classes'] as $class ) {
			$content = str_replace( 'use ' . $prefix . '\\' . $class . ';', '', $content );
			$content = str_replace( '\\' . $prefix . '\\' . $class, '\\' . $class, $content );
		}

		return $content;
	};

	return array(
		'finders'            => $overrides['finders'] ?? array(),

		'exclude-namespaces' => array_merge(
			array( 'Psr' ),
			$overrides['exclude_namespaces'] ?? array()
		),

		'exclude-classes'    => array_merge(
			$wp_calls['classes'],
			$overrides['exclude_classes'] ?? array()
		),
		'exclude-functions'  => array_merge(
			$wp_calls['functions'],
			$overrides['exclude_functions'] ?? array()
		),

		'patchers'           => array_merge(
			array( $wp_reference_stripper ),
			$overrides['patchers'] ?? array()
		),
	);
};
