name: PHP Quality Assurance

on:
  workflow_call:
    inputs:
      plugin-path:
        description: 'Path to the plugin (relative to repo root)'
        type: string
        required: false
        default: '.'
      php-version:
        description: 'PHP version to run QA against'
        type: string
        required: false
        default: '8.5'
      phpcs-config:
        description: 'Path to PHPCS ruleset file (relative to plugin-path)'
        type: string
        required: false
        default: './phpcs.dist.xml'
      phpstan-config:
        description: 'Path to PHPStan config file (relative to plugin-path)'
        type: string
        required: false
        default: './phpstan.dist.neon'

permissions:
  contents: read

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4
        with:
          working-directory: ${{ inputs.plugin-path }}
          composer-options: '--prefer-dist'
      - name: Run PHPCS
        working-directory: ${{ inputs.plugin-path }}
        run: vendor/bin/phpcs --standard=${{ inputs.phpcs-config }} --basepath=. ./ -v --report=full

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4
        with:
          working-directory: ${{ inputs.plugin-path }}
          composer-options: '--prefer-dist'
      - name: Run PHPStan
        working-directory: ${{ inputs.plugin-path }}
        run: vendor/bin/phpstan analyse -c ${{ inputs.phpstan-config }} -v --memory-limit=1G --no-progress
