name: PHP Quality Assurance

on:
  workflow_call:
    inputs:
      plugin-path:
        description: 'Path to the plugin (relative to repo root)'
        type: string
        required: false
        default: '.'
      php-version:
        description: 'PHP version to run QA against'
        type: string
        required: false
        default: '8.5'
      phpcs-config:
        description: 'Path to PHPCS ruleset file (relative to plugin-path)'
        type: string
        required: false
        default: './phpcs.dist.xml'
      phpstan-config:
        description: 'Path to PHPStan config file (relative to plugin-path)'
        type: string
        required: false
        default: './phpstan.dist.neon'

permissions:
  contents: read

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
        with:
          working-directory: ${{ inputs.plugin-path }}
          composer-options: '--prefer-dist'
      - name: Run PHPCS
        working-directory: ${{ inputs.plugin-path }}
        env:
          PHPCS_CONFIG: ${{ inputs.phpcs-config }}
        run: vendor/bin/phpcs --standard=$PHPCS_CONFIG --basepath=. ./ -v --report=full

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
        with:
          working-directory: ${{ inputs.plugin-path }}
          composer-options: '--prefer-dist'
      - name: Run PHPStan
        working-directory: ${{ inputs.plugin-path }}
        env:
          PHPSTAN_CONFIG: ${{ inputs.phpstan-config }}
        run: vendor/bin/phpstan analyse -c $PHPSTAN_CONFIG -v --memory-limit=1G --no-progress
